# Base configs
#baseurl: "https://nategrebelsky.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally

galleries:
  - title: "Thailand"
    folderName: "Thailand"
  - title: "Washington"
    folderName: "Washington"

image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Nate Grebelsky"
footer:
 name: "Nate Grebelsky"
 bio: ""

social_urls:
  instagram: "https://www.instagram.com/nategreb"
  linkedin: "https://www.linkedin.com/in/nate-grebelsky/"
  github: "https://github.com/nategreb"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'